### ISSUE TITLE
Read through math search engine paper

### ISSUE THREAD

**Issue by JennySG** [Tutoron/natural-language#4]
As title

**Comment by tianhaoz95** [comment]
The missing part from their paper: [Tangent search engine](https://arxiv.org/pdf/1507.06235.pdf)

**Comment by tianhaoz95** [comment]
* Order sensitive.
* Math formula aware but not math-aware.
* Interface is usable.
* Data is usable.

**Comment by JennySG** [comment]
I am just a bit confused: is this piece of work/software just started?

 - I think the paper is of different use case, may not be very relevant to our project
 - Agree with Jason: data usable
 - Section 4.3 worth more research (some references very useful)
 - recognition or explanation?
